---
apiVersion: v1
kind: Service
metadata:
  name: mj-test
  namespace: resource-watcher-coordinator
spec:
  ports:
  - name: test
    port: 8080
    protocol: TCP
  selector:
    app: mj-test
  sessionAffinity: None
  type: ClusterIP

